name: remote ssh command
on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ADDRESS }}
        username: root
        password: ${{ secrets.PASSWORD }}
        port: 22  
        script: |
              cd embedded-repl/
              git pull
              docker-compose up -d --build app